### ISSUE TITLE
crash 2168-0001(2xa8)

### ISSUE THREAD

**Issue by rubensk8er** [masagrator/SaltyNX#15]
after installing salty got this error like in some homebrew like awoo or goldleaf dont know why

**Comment by masagrator** [comment]
Literally your info gives me nothing because going by info you have provided I cannot reproduce error - it works fine for me. But I don't know if we are using the same FW, the same CFW, the same method of running homebrew, if we have the same set of sysmodules, etc. etc.

Give me all info. Like literally all you can.
