### ISSUE TITLE
SaltySD (NX-FPS) + Edizon break somes cheats

### ISSUE THREAD

**Issue by deejay87** [masagrator/SaltyNX#4]
FIRMWARE 10.0.0 
ATMOSPHERE 0.11.1

Don't know where to write exactly, sorry if it's not here
All Tesla setup, everything work perfectly, but for Edizon somes lot of cheats are broken, don't know if it's a problem of "Edizon" or "SaltySD", but if i remove, everything is ok,  is just to relate what i see

**Comment by masagrator** [comment]
For 99% this is not an issue of SaltyNX and any of its plugins.
Only Status Monitor can be blamed here if anything happened, because both are using force cheat process. But if this would be an issue, then it would occur also with just one cheat, and I have tested with few cheats that this is not it. So I would search issue in Edizon Overlay.
